version: '3'
services:
  app:
    container_name: node_app
    build:
      dockerfile: Dockerfile
    image: node_image
    ports:
      - "4022:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
