version: '3'
services:
  app:
    container_name: node
    build:
      dockerfile: Dockerfile
    image: node_image
    ports:
      - "4020:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
